In [148]:
import pandas as pd

Create Dataframe

In [149]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Aman"],
    "Age": [20, 21, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)
print(df)

#Empty DataFrame    

df = pd.DataFrame()
print(df)

    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     90
2   Aman   20     78
Empty DataFrame
Columns: []
Index: []

Basic DataFrame Understanding

In [150]:
data = {
    "Name": ["Rahul", "Priya", "Aman"],
    "Age": [20, 21, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

#head()
#Data ki starting rows dekhne ke liye.

print(df.head())
print(df.head(2))

#tail()
#Data ki last rows dekhne ke liye.
print(df.tail())
print(df.tail(2))

#shape()
#Rows aur columns ki sankhya.
print(df.shape)

#columns()
#Columns ke naam dekhne ke liye.
print(df.columns)

#dtypes()
#Columns ke data types dekhne ke liye.
print(df.dtypes)

#ds.info()
#DataFrame ke baare me jankari dekhne ke liye.
print(df.info())

    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     90
2   Aman   20     78
    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     90
    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     90
2   Aman   20     78
    Name  Age  Marks
1  Priya   21     90
2   Aman   20     78
(3, 3)
Index(['Name', 'Age', 'Marks'], dtype='str')
Name       str
Age      int64
Marks    int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes
None

Save DataFrame to CSV(Comma-Seperated Values)

In [151]:
#Pehle ek DataFrame banate hain.

import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Aman"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 72]
}

df = pd.DataFrame(data)

print(df)

#Ab is DataFrame ko CSV file mein save karenge.

df.to_csv("students.csv", index=False )

    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     90
2   Aman   19     72

To Load Data from CSV(Comma-Seperated Values)

In [152]:
df=pd.read_csv

Rows and Columns Selection

In [153]:

import pandas as pd

# ==================================================
# 1. CREATE A SUITABLE DATAFRAME
# ==================================================

data = {
    "Name": ["Rahul", "Priya", "Aman", "Neha", "Rohit"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 72, 95, 80],
    "City": ["Delhi", "Noida", "Delhi", "Ghaziabad", "Noida"]
}

# Convert dictionary into a DataFrame
df = pd.DataFrame(data)

# Display the complete DataFrame
print("ORIGINAL DATAFRAME:")
print(df)


# ==================================================
# 2. SELECT A SINGLE COLUMN
# ==================================================

# Select only the Name column
# Returns a Series
print("\n1. SINGLE COLUMN - NAME:")
print(df["Name"])


# ==================================================
# 3. SELECT MULTIPLE COLUMNS
# ==================================================

# Select Name and Marks columns
# Returns a DataFrame
print("\n2. MULTIPLE COLUMNS - NAME AND MARKS:")
print(df[["Name", "Marks"]])


# ==================================================
# 4. SELECT A SINGLE ROW USING iloc
# ==================================================

# Select the first row by integer position
# Positions start from 0
print("\n3. FIRST ROW USING iloc:")
print(df.iloc[0])


# ==================================================
# 5. SELECT MULTIPLE ROWS USING iloc
# ==================================================

# Select the first three rows
# The ending position 3 is excluded
print("\n4. FIRST THREE ROWS:")
print(df.iloc[0:3])


# ==================================================
# 6. SELECT A ROW USING loc
# ==================================================

# Select the row whose index label is 2
print("\n5. ROW WITH INDEX LABEL 2:")
print(df.loc[2])


# ==================================================
# 7. SELECT ROWS AND COLUMNS TOGETHER
# ==================================================

# Select the first row and Name and Marks columns
print("\n6. FIRST ROW - NAME AND MARKS:")
print(df.loc[0, ["Name", "Marks"]])

# Select the first three rows and first two columns
print("\n7. FIRST THREE ROWS AND FIRST TWO COLUMNS:")
print(df.iloc[0:3, 0:2])


# ==================================================
# 8. SELECT ROWS USING A CONDITION
# ==================================================

# Select students whose marks are greater than 85
print("\n8. STUDENTS WITH MARKS GREATER THAN 85:")
print(df[df["Marks"] > 85])


# ==================================================
# 9. SELECT ROWS USING MULTIPLE CONDITIONS
# ==================================================

# Select students who live in Delhi
# AND have marks greater than 80
print("\n9. DELHI STUDENTS WITH MARKS ABOVE 80:")
result = df[
    (df["City"] == "Delhi") &
    (df["Marks"] > 80)
]
print(result)


# ==================================================
# 10. SELECT MARKS GREATER THAN OR EQUAL TO 80
# ==================================================

# The >= operator also includes students scoring 80
print("\n10. STUDENTS WITH MARKS >= 80:")
print(df[df["Marks"] >= 80])

ORIGINAL DATAFRAME:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
2   Aman   19     72      Delhi
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida

1. SINGLE COLUMN - NAME:
0    Rahul
1    Priya
2     Aman
3     Neha
4    Rohit
Name: Name, dtype: str

2. MULTIPLE COLUMNS - NAME AND MARKS:
    Name  Marks
0  Rahul     85
1  Priya     90
2   Aman     72
3   Neha     95
4  Rohit     80

3. FIRST ROW USING iloc:
Name     Rahul
Age         20
Marks       85
City     Delhi
Name: 0, dtype: object

4. FIRST THREE ROWS:
    Name  Age  Marks   City
0  Rahul   20     85  Delhi
1  Priya   21     90  Noida
2   Aman   19     72  Delhi

5. ROW WITH INDEX LABEL 2:
Name      Aman
Age         19
Marks       72
City     Delhi
Name: 2, dtype: object

6. FIRST ROW - NAME AND MARKS:
Name     Rahul
Marks       85
Name: 0, dtype: object

7. FIRST THREE ROWS AND FIRST TWO COLUMNS:
    Name  Age
0  Rahul   20
1  Priya   21
2   Aman   19

8. STUDENTS WITH MARKS GREATER THAN 85:
    Name  Age  Marks       City
1  Priya   21     90      Noida
3   Neha   22     95  Ghaziabad

9. DELHI STUDENTS WITH MARKS ABOVE 80:
    Name  Age  Marks   City
0  Rahul   20     85  Delhi

10. STUDENTS WITH MARKS >= 80:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida

Filter DataFrame

In [154]:

import pandas as pd

# 1. Create DataFrame
data = {
    "Name": ["Rahul", "Priya", "Aman", "Neha", "Rohit"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 72, 95, 80],
    "City": ["Delhi", "Noida", "Delhi", "Ghaziabad", "Noida"]
}

df = pd.DataFrame(data)

print("ORIGINAL DATAFRAME:")
print(df)


# 2. Filter marks greater than 80
print("\n1. MARKS > 80:")
print(df[df["Marks"] > 80])


# 3. Filter age less than 21
print("\n2. AGE < 21:")
print(df[df["Age"] < 21])


# 4. Filter students from Delhi
print("\n3. CITY IS DELHI:")
print(df[df["City"] == "Delhi"])


# 5. Filter marks greater than or equal to 80
print("\n4. MARKS >= 80:")
print(df[df["Marks"] >= 80])


# 6. AND: Both conditions must be True
print("\n5. DELHI AND MARKS > 80:")
print(df[(df["City"] == "Delhi") & (df["Marks"] > 80)])


# 7. OR: At least one condition must be True
print("\n6. DELHI OR NOIDA:")
print(df[(df["City"] == "Delhi") | (df["City"] == "Noida")])


# 8. Filter multiple specific cities using isin()
print("\n7. USING isin():")
print(df[df["City"].isin(["Delhi", "Noida"])])


# 9. Filter rows and select specific columns
print("\n8. SELECTED ROWS AND COLUMNS:")
print(df.loc[df["Marks"] >= 80, ["Name", "Marks"]])

ORIGINAL DATAFRAME:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
2   Aman   19     72      Delhi
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida

1. MARKS > 80:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
3   Neha   22     95  Ghaziabad

2. AGE < 21:
    Name  Age  Marks   City
0  Rahul   20     85  Delhi
2   Aman   19     72  Delhi
4  Rohit   20     80  Noida

3. CITY IS DELHI:
    Name  Age  Marks   City
0  Rahul   20     85  Delhi
2   Aman   19     72  Delhi

4. MARKS >= 80:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida

5. DELHI AND MARKS > 80:
    Name  Age  Marks   City
0  Rahul   20     85  Delhi

6. DELHI OR NOIDA:
    Name  Age  Marks   City
0  Rahul   20     85  Delhi
1  Priya   21     90  Noida
2   Aman   19     72  Delhi
4  Rohit   20     80  Noida

7. USING isin():
    Name  Age  Marks   City
0  Rahul   20     85  Delhi
1  Priya   21     90  Noida
2   Aman   19     72  Delhi
4  Rohit   20     80  Noida

8. SELECTED ROWS AND COLUMNS:
    Name  Marks
0  Rahul     85
1  Priya     90
3   Neha     95
4  Rohit     80

Rows and Columns Operation

In [155]:

import pandas as pd

# ==========================================
# 1. CREATE DATAFRAME
# ==========================================

data = {
    "Name": ["Rahul", "Priya", "Aman", "Neha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 90, 72, 95],
    "City": ["Delhi", "Noida", "Delhi", "Ghaziabad"]
}

df1 = pd.DataFrame(data)

print("ORIGINAL DATAFRAME:")
print(df1)


# ==========================================
# 2. ADD A NEW COLUMN
# ==========================================

#df1 = df.copy()

df1["Result"] = ["Pass", "Pass", "Pass", "Pass"]

print("\n1. ADD COLUMN:")
print(df)


# ==========================================
# 3. MODIFY AN EXISTING COLUMN
# ==========================================

df2 = df.copy()

df2["Marks"] = df2["Marks"] + 5

print("\n2. MODIFY MARKS:")
print(df2)


# ==========================================
# 4. RENAME A COLUMN
# ==========================================

df3 = df.rename(columns={"Marks": "Score"})

print("\n3. RENAME COLUMN:")
print(df3)


# ==========================================
# 5. DELETE A COLUMN
# ==========================================

df4 = df.drop(columns=["City"])

print("\n4. DELETE CITY COLUMN:")
print(df4)


# ==========================================
# 6. ADD A NEW ROW
# ==========================================

new_row = pd.DataFrame([{
    "Name": "Karan",
    "Age": 21,
    "Marks": 88,
    "City": "Delhi"
}])

df5 = pd.concat([df, new_row], ignore_index=True)

print("\n5. ADD NEW ROW:")
print(df5)


# ==========================================
# 7. DELETE A ROW BY INDEX LABEL
# ==========================================

df6 = df.drop(index=2)

print("\n6. DELETE ROW WITH INDEX LABEL 2:")
print(df6)


# ==========================================
# 8. FILTER ROWS BY CONDITION
# ==========================================

df7 = df[df["Marks"] >= 80]

print("\n7. STUDENTS WITH MARKS >= 80:")
print(df7)

ORIGINAL DATAFRAME:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
2   Aman   19     72      Delhi
3   Neha   22     95  Ghaziabad

1. ADD COLUMN:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
2   Aman   19     72      Delhi
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida

2. MODIFY MARKS:
    Name  Age  Marks       City
0  Rahul   20     90      Delhi
1  Priya   21     95      Noida
2   Aman   19     77      Delhi
3   Neha   22    100  Ghaziabad
4  Rohit   20     85      Noida

3. RENAME COLUMN:
    Name  Age  Score       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
2   Aman   19     72      Delhi
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida

4. DELETE CITY COLUMN:
    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     90
2   Aman   19     72
3   Neha   22     95
4  Rohit   20     80

5. ADD NEW ROW:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
2   Aman   19     72      Delhi
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida
5  Karan   21     88      Delhi

6. DELETE ROW WITH INDEX LABEL 2:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida

7. STUDENTS WITH MARKS >= 80:
    Name  Age  Marks       City
0  Rahul   20     85      Delhi
1  Priya   21     90      Noida
3   Neha   22     95  Ghaziabad
4  Rohit   20     80      Noida

In [156]:
data={
    "Name": ["Rahul", "Priya", "Aman", "Shubham"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 90, 72, 88],
    "monthly salary":[40000, 50000, 60000, 70000]
}

df=pd.DataFrame(data)



#add a row in the dataframe using loc

df.loc[len(df)]=["Anjali", 20, 92, "Noida"]

#update a value in the dataframe using loc

df.loc[0,"monthly salary"]=50000    

#update value - using index name

df.loc[df["Name"]=="Priya","monthly salary"]=60000

#delete value -row and columns values

df.drop(df[df["Name"]=="Aman"].index, inplace=True)  #delete row  , axis=0 for row and axis=1 for column    


#delete column

df.drop("monthly salary", axis=1, inplace=True)  #delete column 


#sort values

df.sort_values(by="Marks", ascending=False, inplace=True)  #sort by marks in descending order

Working with data values

In [157]:
import pandas as pd

df['DOJ']=["2020-01-15", "2021-03-22", "2019-07-10", "2022-05-30"]  # Adding a new column 'DOJ' (Date of Joining) to the DataFrame

print(df)

df['DOJ'] = pd.to_datetime(df['DOJ'])  # Convert the 'DOJ' column to datetime format
print(df['DOJ'].dtype)  # Check the data type of the 'DOJ' column   

df1=df
df1['DOJ2']=['01/15/2020', '03/22/2021', '07/10/2019', '05/30/2022']  # Adding a new column 'doj2' with date strings in different format  


df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format='%m/%d/%Y') 
 # Convert the 'DOJ2' column to datetime format with specified format
df1

df=df.drop('DOJ2', axis=1)  # Drop the 'DOJ2' column from the DataFrame
df

      Name  Age  Marks         DOJ
4   Anjali   20     92  2020-01-15
1    Priya   21     90  2021-03-22
3  Shubham   22     88  2019-07-10
0    Rahul   20     85  2022-05-30
datetime64[us]

      Name  Age  Marks        DOJ
4   Anjali   20     92 2020-01-15
1    Priya   21     90 2021-03-22
3  Shubham   22     88 2019-07-10
0    Rahul   20     85 2022-05-30

In [158]:
#extract year month date week


print(df['DOJ'].dt.year)

print(df['DOJ'].dt.month)

print(df['DOJ'].dt.day)

print(df['DOJ'].dt.day_name())

4    2020
1    2021
3    2019
0    2022
Name: DOJ, dtype: int32
4    1
1    3
3    7
0    5
Name: DOJ, dtype: int32
4    15
1    22
3    10
0    30
Name: DOJ, dtype: int32
4    Wednesday
1       Monday
3    Wednesday
0       Monday
Name: DOJ, dtype: str

In [159]:
df['DOJ']+pd.Timedelta(days=90)

4   2020-04-14
1   2021-06-20
3   2019-10-08
0   2022-08-28
Name: DOJ, dtype: datetime64[us]

Handling Missing Values

In [160]:
import numpy as np

df.isnull()
df.loc[df.Name == 'Rahul', 'Marks'] = 77

df

      Name  Age  Marks        DOJ
4   Anjali   20     92 2020-01-15
1    Priya   21     90 2021-03-22
3  Shubham   22     88 2019-07-10
0    Rahul   20     77 2022-05-30

In [161]:
df.isnull().sum()

Name     0
Age      0
Marks    0
DOJ      0
dtype: int64

In [162]:
df.fillna(89)

      Name  Age  Marks        DOJ
4   Anjali   20     92 2020-01-15
1    Priya   21     90 2021-03-22
3  Shubham   22     88 2019-07-10
0    Rahul   20     77 2022-05-30

Aggregation and group by

In [163]:
(df['Marks'].value_counts())

Marks
92    1
90    1
88    1
77    1
Name: count, dtype: int64

In [164]:
df[df['Marks'] == 92.0].value_counts()

Name    Age  Marks  DOJ
Anjali  20   92     2020-01-15    1
Name: count, dtype: int64

In [165]:
df.groupby('Age')['Marks'].sum()

Age
20    169
21     90
22     88
Name: Marks, dtype: int64

In [168]:
df.groupby('Age').agg({'Marks':'mean', 'Name':'count'})

     Marks  Name
Age
20    84.5     2
21    90.0     1
22    88.0     1

Concaterate and Merge Dataframe(JOINS)

In [ ]:
df1=pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

df2=pd.DataFrame({'ID':[1,2,3,4],'Score':[88,96,77,79]})
df2

print(pd.concat([df1,df2],axis=0)) #vertical/row level/top on top

print(pd.concat([df1,df2],axis=1)) # horizontal/column level/side on side

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   3  NaN   77.0
3   4  NaN   79.0
    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   3     77
3  NaN  NaN   4     79

In [176]:
#merge = join

pd.merge(df1,df2,how='outer',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77
3   4  NaN     79

In [177]:
pd.merge(df1,df2,how='outer',left_on='ID',right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77
3   4  NaN     79